insert into public.cheeses (
  slug,
  name,
  creamery_name,
  location_city,
  location_region,
  location_country,
  milk_type,
  rennet,
  cheese_style,
  age_description,
  flavor_profile,
  story_notes,
  pairings,
  status,
  submitted_by,
  approved_by
)
values (
  'shelburne-2-year',
  'Shelburne 2 Year',
  'Shelburne Farms',
  'Shelburne',
  'Vermont',
  'USA',
  'Raw cow’s milk',
  'Animal',
  'Cheddar',
  'Minimum two years',
  array['Brothy', 'Caramelized onions', 'Toasted nuts'],
  'Uses a pasture-raised Brown Swiss herd and is processed by hand. A classic Vermont-style cheddar.',
  array[
    'Granny Smith apples',
    'Crisp pears',
    'Raw honey',
    'Fig spread',
    'Sourdough bread',
    'Cabernet Sauvignon',
    'Merlot',
    'Oaked Chardonnay',
    'Dry Riesling'
  ],
  'published',
  '296fb853-d174-46c7-8e94-e19b1ce61fd2',
  '296fb853-d174-46c7-8e94-e19b1ce61fd2'
)
on conflict (slug) do update set
  name = excluded.name,
  creamery_name = excluded.creamery_name,
  location_city = excluded.location_city,
  location_region = excluded.location_region,
  location_country = excluded.location_country,
  milk_type = excluded.milk_type,
  rennet = excluded.rennet,
  cheese_style = excluded.cheese_style,
  age_description = excluded.age_description,
  flavor_profile = excluded.flavor_profile,
  story_notes = excluded.story_notes,
  pairings = excluded.pairings,
  status = 'published',
  approved_by = excluded.approved_by,
  updated_at = now();
